"""empty message

Revision ID: 5dc77f7b2ebe
Revises: fe89ce1a60c6
Create Date: 2017-07-21 14:10:10.353000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5dc77f7b2ebe'
down_revision = 'fe89ce1a60c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('service', sa.Column('notice', sa.Boolean(), nullable=True))
    op.add_column('service', sa.Column('shortcut', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'shortcut')
    op.drop_column('service', 'notice')
    # ### end Alembic commands ###
