"""empty message

Revision ID: 8282f20fbbe3
Revises: 5dc77f7b2ebe
Create Date: 2017-07-24 09:15:08.976000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8282f20fbbe3'
down_revision = '5dc77f7b2ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=True),
    sa.Column('leave_time', sa.DateTime(), nullable=True),
    sa.Column('leave_user', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['leave_user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message')
    # ### end Alembic commands ###
