"""empty message

Revision ID: c9dc58970e0c
Revises: f9ba1a2d5275
Create Date: 2017-08-09 15:04:18.901000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9dc58970e0c'
down_revision = 'f9ba1a2d5275'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('setting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('application_name', sa.String(length=50), nullable=True),
    sa.Column('gitlab_url', sa.String(length=120), nullable=True),
    sa.Column('client_id', sa.String(length=120), nullable=True),
    sa.Column('client_secret', sa.String(length=120), nullable=True),
    sa.Column('redirect_uri', sa.String(length=120), nullable=True),
    sa.Column('redirect_server', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('application_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('setting')
    # ### end Alembic commands ###
