"""empty message

Revision ID: cceae9204d7e
Revises: c9dc58970e0c
Create Date: 2017-08-09 18:06:18.590000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cceae9204d7e'
down_revision = 'c9dc58970e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('access_token', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'access_token')
    # ### end Alembic commands ###
