"""empty message

Revision ID: f086b99c0431
Revises: 0a99434b5155
Create Date: 2017-08-15 14:57:03.763000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f086b99c0431'
down_revision = '0a99434b5155'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notice', sa.Column('link', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notice', 'link')
    # ### end Alembic commands ###
