"""empty message

Revision ID: fefc39b2abc7
Revises: 0ad5001838f7
Create Date: 2017-07-26 11:14:16.515000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fefc39b2abc7'
down_revision = '0ad5001838f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'service_ibfk_2', 'service', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(u'service_ibfk_2', 'service', 'user', ['update_user'], ['id'])
    # ### end Alembic commands ###
